apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: app-node
  namespace: andiapp
spec:
  selector:
    matchLabels:
      app: app-node
  replicas: 1
  template:
    metadata:
      labels:
        app: app-node
    spec:
      containers:
      - name: app-node
        image: andikapri/nodejs:6761760104
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: app-node
  namespace: andiapp
  labels:
    app: app-node
spec:
  selector:
    app: app-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080